# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-06 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newsletterrecepients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLetterRecepients',
            new_name='NewsLetterRecipients',
        ),
    ]
